accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url("login/$", views.Login.as_view(), name='login'),
    url("logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url("signup/$", views.signup, name="signup"),
    url("change-password/$", views.change_password, name="change_password"),
]

bank/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('customers/', include('customers.urls')),
    path('', include('website.urls'))
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile', views.profile, name='profile'),
    path('history', views.history, name='history'),
    path('send-money', views.send, name='send_money')
]

website/urls.py
from django.urls import path

from .import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('gallery', views.gallery, name='gallery')
]

website/models.py
from django.db import models
import datetime
# Create your forms here.

class Contact(models.Model):
	name = models.CharField(max_length=120)
	email = models.EmailField(max_length=120)
	message = models.CharField(max_length=500)
	timestamp = models.DateTimeField(blank=True, default=datetime.datetime.now())

	def __str__(self):
		return self.email

	class Meta:
		ordering = ['-timestamp']

website/forms.py
from django import forms
from .models import Contact


class ContactUsForm(forms.ModelForm):
    # name = forms.CharField(widget=forms.TextInput())
    # email = forms.CharField(widget=forms.TextInput())
    # message = forms.CharField(widget=forms.Textarea())
	
    class Meta:
        model = Contact
        fields = ('name', 'email','message')

website/views.py
from django.shortcuts import render, redirect

from .forms import ContactUsForm

# from django.shortcuts import render_to_response
# from django.template import RequestContext

def home(request):
    title = 'home'
    return render(request, "website/home.html" , {'title':home})

def about(request):
    title = 'about'
    return render(request, "website/about.html", {'title':about})


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST or None)
        if form.is_valid():
            form.save()
            # this_form.save()
            return redirect('website:home')
	# return render_to_response('website/contact.html', {'form':form}, RequestContext(request))
    return render(request, "website/contact.html", {'title':contact})

def gallery(request):
    title = 'gallery'
    return render(request, "website/gallery.html", {'title':gallery})

def services(request):
    title = 'services'
    return render(request, "website/services.html", {'title':services})

website/templates/website/about.html
{% extends "website/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <!-- about -->
	<div class=" w3ls-section" id="inner-about">
		<div class="container">
			<h3 class="h3-w3l">about us</h3>
			<!-- about bottom-->
			<div class="about-bottom">
				<div class="col-md-6 about-w3right">
					
				</div>
				<div class="col-md-6 about-w3left"> 
					<p>
							We’re a leading financial services provider with over 25 years of banking operations in the U.S. We’ve been helping businesses and individuals achieve their ambitions, while transforming lives and supporting U.S’s growth agenda.
							PGA Bank Limited combines its expertise, rich knowledge and experience of the local environment, to bring the best of banking to its customers and clients.
					</p>
				</div> 
				<div class="clearfix"> </div>
			</div>		
		</div>	
			<!-- //about-bottom -->
	</div>
	<!-- //about -->
{% endblock %}

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="E-Bankingn" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="{% static "css/bootstrap.css" %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static "css/style.css" %}" type="text/css" rel="stylesheet" media="all">
    <link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
    <!-- font-awesome icons -->
    <!-- //Custom Theme files -->
    <!-- js -->
    <script src="{% static "js/jquery-2.2.3.min.js" %}"></script>
    <!-- web-fonts -->
    <link href="//fonts.googleapis.com/css?family=Secular+One" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <!-- //web-fonts -->

</head>

<body>

    <!-- header -->
    <div class="headerw3-agile">
        <div class="header-w3mdl">
            <!-- header-two -->
            <div class="container">
                <div class="agileits-logo navbar-left">
                    <h1>
                        <a href="{% url "website:home" %}">
                            <!-- <img src="images/e.png" alt="logo" /-->PGA BANK</a>
                    </h1>
                </div>
                <div class="agileits-hdright nav navbar-nav">
                    <div class="header-w3top">
                        <!-- header-top -->
                        <ul class="w3l-nav-top">
                            <li>
                                <i class="fa fa-phone"></i>
                                <span> +01 222 111 444 </span>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'customers:dashboard' %}">
                                    <i class="fa fa-user" aria-hidden="true">{{request.user.email}}</i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:logout' %}">
                                    <i class="fa fa-logout" aria-hidden="true">Log Out</i>
                                </a>
                            </li>
                            {% endif %}
                            {% if not request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'accounts:signup' %}">
                                    <i class="fa fa-signup" aria-hidden="true">Sign Up</i>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:login' %}">
                                    <i class="fa fa-login" aria-hidden="true">Log In</i>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                        <div class="clearfix"> </div>
                    </div>
                    <!-- <div class="agile_social_banner">
                        <ul style="list-style: none;">


                        </ul>
                    </div> -->

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- //header -->
    <!-- banner -->


    <!-- banner -->
    <div class="banner inner-banner">
        <div class="header-nav">
            <!-- header-three -->
            <nav class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        Menu
                    </button>
                </div>
                <!-- top-nav -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="{% url 'website:home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'website:about' %}">About</a>
                        </li>
                        <li>
                            <a href="{% url 'website:services' %}">Services</a>
                        </li>
                        <li>
                            <a href="{% url 'website:gallery' %}">Gallery</a>
                        </li>
                        <li>
                            <a href="{% url 'website:contact' %}">Contact</a>
                        </li>
                    </ul>
                    <div class="clearfix"> </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- banner -->




    {% block content %} {% endblock %}

    <!--footer-->
    <div class="agile-footer w3ls-section">
            <div class="container">
                <div class="col-md-7 list-footer">
                    <ul class="footer-nav">
                        <li>
                            <a href="{% url 'website:home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'website:about' %}">About</a>
                        </li>
                        <li>
                            <a href="{% url 'website:services' %}">Services</a>
                        </li>
                        <li>
                            <a href="{% url 'website:gallery' %}">Gallery</a>
                        </li>
                        <li>
                            <a href="{% url 'website:contact' %}">Contact</a>
                        </li>
                    </ul>
                    
                </div>
                <!-- <div class="col-md-5 agileinfo-sub">
                    <h6>Click the link below to start the subscription service</h6>
                    <a href="#" data-toggle="modal" data-target="#myModal1">subscribe</a>
                </div> -->
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- <div class="w3_agile-copyright text-center">
            <p>© 2017 E-Banking. All rights reserved | Design by <a href="//w3layouts.com/">W3layouts</a></p>
        </div> -->
        <!--//footer-->
        <!-- modal-sign -->
        <!-- <div class="modal bnr-modal fade" id="myModal" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-dialog modal-md">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                            <img src="images/logo.png" alt="logo" />
                        </div>
                        <div class="modal-body">
                            <img src="images/modal.jpg" class="img-responsive" alt="image">
                            <p>Fusce et congue nibh, ut ullamcorper magna. Donec ac massa tincidunt, fringilla sapien vel, tempus massa. Vestibulum felis leo, tincidunt sit amet tristique accumsan. In vitae dapibus metus. Donec nec massa non nulla mattis aliquam egestas et mi.</p>
                        </div>
                    </div>
                </div>
    
            </div>
        </div> -->
        <!-- modal-sign -->
        <!-- <div class="modal bnr-modal fade" id="myModal1" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <img src="images/logo.png" alt="logo" />
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body modal-spa">
                        <p>E-Banking's email newsletter provides subscribers with helpful articles on important issues in the banking industry, as well as news about events and more! To sign up for the newsletter, fill the below form.</p>
                        <form class=" wthree-subsribe" action="#" method="post">
                            <input type="text" name="name" placeholder="Your Name" required="">
                            <input type="email" name="email" placeholder="your Email" required="">
                            <input type="submit" value="SignUp">
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div> -->
        <!-- //modal-sign -->
        <!-- //banner -->
        <!-- //banner-text -->
        <!-- //banner -->
        <!-- banner Slider starts Here -->
    <script src="{% static "js/responsiveslides.min.js" %}"></script>
    <script>
        // You can also use "$(window).load(function() {"
        $(function () {
            // Slideshow 3
            $("#slider3").responsiveSlides({
                auto: true,
                pager: false,
                nav: true,
                speed: 500,
                namespace: "callbacks",
                before: function () {
                    $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                    $('.events').append("<li>after event fired.</li>");
                }
            });

        });
    </script>
    <script src="{% static "js/SmoothScroll.min.js" %}"></script>
    <!-- smooth-scrolling-of-move-up -->
    <script type="text/javascript" src="{% static "js/move-top.js" %}"></script>
    <script type="text/javascript" src="{% static "js/easing.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            /*
            var defaults = {
                containerID: 'toTop', // fading element id
                containerHoverID: 'toTopHover', // fading element hover id
                scrollSpeed: 1200,
                easingType: 'linear'
            };
            */

            $().UItoTop({ easingType: 'easeOutQuart' });

        });
    </script>
    <!-- //smooth-scrolling-of-move-up -->

</body>

</html>

website/templates/website/contact.html
{% extends "website/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  	<!-- contact -->
	<div class="w3ls-section contact">
		<div class="container"> 
			<div class="w3ls-title">
				<h2 class="h3-w3l">contact us</h2> 
			</div>  
			<div class="w3ls_map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d48306.05339877067!2d-74.245183970742!3d40.825144655510556!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c2555646a723a1%3A0x449f3366d017b214!2sMontclair%2C+NJ%2C+USA!5e0!3m2!1sen!2sin!4v1465991700675" style="border:0"></iframe>
			</div>
			<div class="contact_wthreerow agileits-w3layouts">
				<div class="col-md-5 agileits_w3layouts_contact_gridl">
					<div class="agileits_mail_grid_right_grid">
						<h4>About Us</h4>
						<p>Itaque earum rerum hic tenetur a sapiente delectus, 
							ut aut reiciendis voluptatibus maiores alias consequatur.</p>
					</div> 
					<div class="agileits_mail_grid_right_grid">
						<h4>Contact Info</h4>
						<ul class="contact_info">
							<li><i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>1234k Avenue, 4th block,3FB,New Jersey.</li>
							<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
							<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
						</ul>
					</div>
				</div>
				<div class="col-md-7 w3l_contact_form">
					<h4>Contact Form</h4> 
					<form method="post">{% csrf_token %}
						<input type="text" name="name" placeholder="Name">
						<input type="email" name="email" placeholder="Email">
						<textarea name="message" placeholder="Message"></textarea>
						<input type="submit" value="Submit">
					</form>
				</div>
				
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //contact --> 
{% endblock %}

website/templates/website/gallery.html
{% extends "website/base.html" %}

{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
  	<!-- gallery -->
	<div class="w3ls-section gallery">
		<div class="container">
			<div class="w3ls-title">
				<h2 class="h3-w3l">Gallery</h2>
			</div>
			<div class="gallery-grids-top">
				<div class="gallery-grids agileits-w3layouts">
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img">
						<a class="example-image-link w3-agilepic" href="{% static "images/g1.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g1.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g2.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g2.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g3.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g3.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img gallery-mdl hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g3.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g3.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img gallery-mdl hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g4.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g4.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g5.jpg" %}" data-lightbox="example-set" data-title="">
						<img class="example-image img-responsive" src="{% static "images/g5.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g6.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g6.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g2.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g2.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-6 gallery-grid-img gallery-mdl hover ehover14">
						<a class="example-image-link w3-agilepic" href="{% static "images/g1.jpg" %}" data-lightbox="example-set" data-title="">
							<img class="example-image img-responsive" src="{% static "images/g1.jpg" %}" alt=""/>
							<div class="w3ls-overlay">
								<h4>Our Gallery</h4>
							</div>
						</a>
					</div>
					<div class="clearfix"> </div>
					<script src="{% static "js/lightbox-plus-jquery.min.js" %}"></script>
				</div>
			</div>
		</div>
	</div>
	<!-- //gallery -->
{% endblock %}

website/templates/website/home.html
{% extends "website/base.home.html" %}

{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
  	<!-- about -->
	<div class="home-about w3ls-section">
		<div class="container">
			<!-- about top-->
			<div class="w3ls-about agile-section">
					<div class="w3-agileits-about-grids">
						<div class="col-md-6 col-sm-6 col-xs-6 agileits-title">
							<h3>what makes us Unique?</h3> 
						</div>
						<div class="col-md-6 col-sm-6 col-xs-6  agile-about-bottom-right">
							<p>We predict that this industry will radically change in the coming 3 to 5 years. Cross-border offshore banking needs are to be redefined, investment services and portfolio management to be professionalised as well as risk and regulations to be optimised. In addition compliance and controls need to be more efficiently designed, a full tax transparency needs to be guaranteed, organisations need to operate more cost efficient and the bank focus belongs to their clients.</p>
							<p class="w3ls-about-text">We are uniquely positioned to assist you in successfully responding to your challenges. We help you not only comply with regulatory requirements but also transform your bank profitably and grow even further in the next decade.</p>
						
						</div>
						<div class="clearfix"> </div>
				   </div>
			</div>
			<!-- //about top-->
			<!-- about bottom-->
			<div class="about-bottom">
				<div class="col-md-6 about-w3right">
					
				</div>
				<div class="col-md-6 about-w3left"> 
					<p>
						We’re a leading financial services provider with over 25 years of banking operations in the U.S. We’ve been helping businesses and individuals achieve their ambitions, while transforming lives and supporting U.S’s growth agenda.
						PGA Bank Limited combines its expertise, rich knowledge and experience of the local environment, to bring the best of banking to its customers and clients.
					</p> 
				</div> 
				<div class="clearfix"> </div>
			</div>		
		</div>	
			<!-- //about-bottom -->
			<!-- about-bottom-grid -->
			<div class="wthree-about-bot-grid-sec">

				<div class="col-md-6  col-sm-6 w3ls-abg w3ls-abg1 abg2">
					<h4>Pay people. Pay bills.Transfer money.</h4>
					<p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
				</div>
				<div class="col-md-6 col-sm-6 w3ls-abg w3ls-abg2 abg3">
					<h4>Mobile Privacy and Security</h4>
					<p>Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.</p>
				</div>
				
				<div class="clearfix"> </div>
			</div>
			<!-- //about-bottom-grid-->
	</div>
	<!-- //about -->

{% endblock %}

website/templates/website/services.html
{% extends "website/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  	<!--services-->
<!--services-->
	<div class="w3ls-section services">
		<div class="container">
			<h2 class="h3-w3l">services</h2> 
			<div class="services-left">
				<h4 class="title">online banking</h4>
				<h5>any time,anywhere.</h5>
				<p class="data">Enim nim pariatur cliche reprehen chardson ad sqderit ad sveprehed sectetur adipiscing elit iatur clic.</p>
				<div class="more">
					<a href="#" data-toggle="modal" data-target="#myModal"> Read More</a>
				</div>
			</div>
			<div class="services-right">
				
				<div class="services-grid">
					<div class="col-md-2 col-sm-2 col-xs-2 sr-icon">
						<span class="fa fa-gg" aria-hidden="true"></span>
					</div>	
					<div class="col-md-10 col-sm-10 col-xs-10 sr-txt">	
						<h5>transfer money</h5>
						<p>Itaque earum rerum hic a sapiente delectus</p>
					</div>
					<div class="clearfix"></div>
				</div>	
				<div class="services-grid">
					<div class="col-md-2 col-sm-2 col-xs-2 sr-icon">
						<span class="fa fa-credit-card-alt" aria-hidden="true"></span>
					</div>	
					<div class="col-md-10 col-sm-10 col-xs-10 sr-txt">	
						<h5>pay bills</h5>
						<p>Itaque earum rerum hic a sapiente delectus</p>
					</div>	
					<div class="clearfix"> </div>
				</div>
				<div class="services-grid">
					<div class="col-md-2 col-sm-2 col-xs-2 sr-icon">
						<span class="fa fa-shopping-cart" aria-hidden="true"></span>
					</div>	
					<div class="col-md-10 col-sm-10 col-xs-10 sr-txt">
						<h5>Shop Online</h5>
						<p>Itaque earum rerum hic a sapiente delectus</p>
					</div>	
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!--//services-->
	<div class="agileits_w3layouts-services-mid">
		<div class="col-md-5 services-mid-img">
		</div>
		<div class="col-md-5 services-mid-text">
		</div>
		<div class="clearfix"> </div>
	</div>
	<div class="w3ls-section">
		<div class="container">  
			<div class="services-w3ls-row agileits-w3layouts">
				<div class="col-md-3 col-sm-3 col-xs-6 services-grid agileits-w3layouts">
					<i class="fa fa-user-secret" aria-hidden="true"></i>
					<h5>Secure Online Banking</h5>
					<p>Sapiente delectus maiores itaque earum rerum hic tenetur a alias phasellus.</p>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 services-grid agileits-w3layouts">
					<i class="fa fa-comments" aria-hidden="true"></i>
					<h5>24/7 Personal Support</h5>
					<p>Tenetur a sapiente itaque earum rerum hic delectus maiores alias phasellus.</p>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 services-grid agileits-w3layouts">
					<i class="fa fa-gift" aria-hidden="true"></i>
					<h5>Gift vouchers</h5>
					<p>Itaque earum rerum hic tenetur a sapiente delectus maiores alias phasellus.</p>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6 services-grid agileits-w3layouts">
					<i class="fa fa-list-alt" aria-hidden="true"></i>
					<h5>insta banking</h5>
					<p>Earum rerum hic tenetur a alias sapiente delectus maiores itaque phasellus.</p>
				</div> 
				<div class="clearfix"> </div>
			</div>  
		</div>
	</div>
	<!-- //services -->

	<!--//services-->
{% endblock %}