accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url("login/$", views.Login.as_view(), name='login'),
    url("logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url("signup/$", views.signup, name="signup"),
    url("change-password/$", views.change_password, name="change_password"),
]

bank/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('customers/', include('customers.urls')),
    path('', include('website.urls'))
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile', views.profile, name='profile'),
    path('history', views.history, name='history'),
    path('send-money', views.send, name='send_money')
]

website/urls.py
from django.urls import path

from .import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('gallery', views.gallery, name='gallery')
]

customers/models.py
import datetime

from django.db import models
from django import forms
from django.conf import settings

class Account(models.Model):
    ACCOUNT_TYPES = (
        ('SA' , 'Savings Account' ),
        ('CA' , 'Current Account' ),
        ('JA' , 'Joint Account' ),
    )
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='accounts', verbose_name='The related user')
    account_type = models.CharField(max_length=2, choices=ACCOUNT_TYPES)
    account_number = models.CharField(max_length=13, unique=True)
    account_balance = models.DecimalField(max_digits=18, decimal_places=2)
    last_deposit = models.DecimalField(max_digits=10, decimal_places=2)
    interest_rate = models.DecimalField(max_digits=3, decimal_places=0)
    date_created = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def __str__(self):
        return self.account_number

    # def save(self, *args, **kwargs):
    #     do_something()
    #     super(Account, self).save(*args, **kwargs) # Call the "real" save() method.


class Transaction(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    from_account = models.CharField(max_length=13)
    to_account = models.CharField(max_length=13)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_created = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def __str__(self):
        return str(self.amount)

customers/forms.py
from django import forms
from .models import Transaction


class TransactionForm(forms.ModelForm):
    from_account = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'From account'}))
    to_account = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control', 'placeholder': 'To account'}))
    amount = forms.CharField(label='',widget=forms.NumberInput(attrs={'class':'form-control', 'placeholder': 'Amount to send'}))

    class Meta:
        model = Transaction
        fields = ('from_account', 'to_account', 'amount',)

customers/views.py
from django.utils import timezone
import decimal
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse

from .forms import Transaction
from . import forms
from accounts.forms import ProfileForm
from .models import Account


@login_required(login_url='../../accounts/login/')
def dashboard(request):
    account = Account.objects.get(owner=request.user)
    return render(request, "customers/dashboard.html", {'account': account})

@login_required(login_url='../../accounts/login/')
def history(request):
    transaction = Transaction.objects.filter(owner=request.user)#.order_by(date_created)
    return render(request, "customers/transactions.html", {'transaction': transaction})


@login_required(login_url='../../accounts/login/')
def send(request):
    if request.method == 'POST':
        form = forms.TransactionForm(request.POST)
        if form.is_valid():
            sender = Account.objects.get(account_number=request.POST.get('from_account'))
            if sender.account_balance > decimal.Decimal(request.POST.get('amount')):

                trans =  form.save()
                trans.owner = request.user
                trans.save()
                
                # debit the sender account
                sender.account_balance -= decimal.Decimal(request.POST.get('amount'))
                sender.save()

                #credit the receiver account
                receiver = Account.objects.get(account_number=request.POST.get('to_account'))
                receiver.account_balance += decimal.Decimal(request.POST.get('amount'))
                receiver.save()

                return HttpResponseRedirect(reverse_lazy('customers:history'))
            # else:
            #     return 
    else:
        form = forms.TransactionForm()
        return render(request, "customers/send_money.html", {'form': form})



@login_required(login_url='../../accounts/login/')
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('customers:profile'))
    else:
        # form = ProfileForm()
        return render(request, "customers/profile.html")

customers/templates/customers/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "customers/assets/img/apple-icon.png" %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static "customers/assets/img/favicon.png" %}">
    <title>
        {% block title %}{% endblock %}
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    
    
    <!-- Bootstrap core CSS     -->
    <link href="{% static "customers/assets/css/bootstrap.min.css" %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static "customers/assets/css/animate.min.css" %}" rel="stylesheet"/>

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static "customers/assets/css/paper-dashboard.css" %}" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static "customers/assets/css/demo.css" %}" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static "customers/assets/css/themify-icons.css" %}" />
</head>

<body>
        <div class="wrapper">
                <div class="sidebar" data-background-color="white" data-active-color="danger">
            
                <!--
                    Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
                    Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
                -->
            
                    <div class="sidebar-wrapper">
                        <div class="logo">
                            <a href="{% url 'website:home' %}" class="simple-text">
                                PGA BANK
                            </a>
                        </div>
            
                        <ul class="nav">
                            <li class="active">
                                <a href="{% url 'customers:dashboard' %}">
                                    <i class="fa fa-dashboard"></i>
                                    <p>Dashboard</p>
                                </a>
                            </li>
                            <li class="">
                                    <a href="{% url 'customers:profile' %}">
                                        <i class="fa fa-user"></i>
                                        <p>User Profile</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'customers:history' %}">
                                        <i class="fa fa-history"></i>
                                        <p>Transactions</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'customers:send_money' %}">
                                        <i class="fa fa-share"></i>
                                        <p>Transfer Funds</p>
                                    </a>
                                </li>
                        </ul>
                    </div>
                </div>
            
                <div class="main-panel">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar bar1"></span>
                                    <span class="icon-bar bar2"></span>
                                    <span class="icon-bar bar3"></span>
                                </button>
                                <a class="navbar-brand" href="#">{{title}}</a>
                            </div>
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                {% if request.user.is_authenticated %}
                                                <i class="fa fa-user"></i>
                                                <p>{{ request.user.email }}</p>
                                                {% endif %}
                                                <b class="caret"></b>
                                          </a>
                                          <ul class="dropdown-menu">
                                            <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                                            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                                          </ul>
                                    </li>
                                </ul>
            
                            </div>
                        </div>
                    </nav>
            
            
                    <div class="content">
                        <div class="container-fluid">
                            {% block content %} 

                            {% endblock %}
                        </div>
                    </div>
            
            
                    <footer class="footer">
                        <div class="container-fluid">
                            <nav class="pull-left">
                                <ul>
            
                                    <li>
                                        <a href="#">
                                            Home
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                            <div class="copyright pull-right">
                                &copy; <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Creative Tim</a>
                            </div>
                        </div>
                    </footer>
            
                </div>
            </div>
</body>


    <!--   Core JS Files   -->
    <script src="{% static "customers/assets/js/jquery-1.10.2.js" %}" type="text/javascript"></script>
	<script src="{% static "customers/assets/js/bootstrap.min.js" %}" type="text/javascript"></script>

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="{% static "customers/assets/js/bootstrap-checkbox-radio.js" %}"></script>

	<!--  Charts Plugin -->
	<script src="{% static "customers/assets/js/chartist.min.js" %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static "customers/assets/js/bootstrap-notify.js" %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

    <!-- Paper Dashboard Core javascript and methods for Demo purpose -->
	<script src="{% static "customers/assets/js/paper-dashboard.js" %}"></script>

	<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
	<!-- <script src="assets/js/demo.js"></script> -->

</html>

customers/templates/customers/dashboard.html
{% extends "customers/base.html" %}

 {% block title %} 
    Dashboard
 {% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-warning text-center">
                            <i class="fa fa-users"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Customers</p>
                            2534
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <hr />
                    <div class="stats">
                        <i class="ti-reload"></i> Updated now
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-success text-center">
                            <i class="fa fa-money"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Balance</p>

                            {% if account %}
                              ${{account.account_balance}}
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <hr />
                    <div class="stats">
                        <i class="ti-calendar"></i> Last day
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-danger text-center">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Visitors</p>
                            23
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <hr />
                    <div class="stats">
                        <i class="fa fa-reload"></i> In the last hour
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="content">
                <div class="row">
                    <div class="col-xs-5">
                        <div class="icon-big icon-info text-center">
                            <i class="fa fa-twitter"></i>
                        </div>
                    </div>
                    <div class="col-xs-7">
                        <div class="numbers">
                            <p>Followers</p>
                            +45
                        </div>
                    </div>
                </div>
                <div class="footer">
                    <hr />
                    <div class="stats">
                        <i class="ti-reload"></i> Updated now
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Users Behavior</h4>
                <p class="category">24 Hours performance</p>
            </div>
            <div class="content">

                <div id="chartHours" class="ct-chart"></div>


                <div class="footer">
                    <div class="chart-legend">
                        <i class="fa fa-circle text-info"></i> Open
                        <i class="fa fa-circle text-danger"></i> Click
                        <i class="fa fa-circle text-warning"></i> Click Second Time
                    </div>
                    <hr>
                    <div class="stats">
                        <i class="ti-reload"></i> Updated 3 minutes ago
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>


        var dataSales = {
            labels: ['9:00AM', '12:00AM', '3:00PM', '6:00PM', '9:00PM', '12:00PM', '3:00AM', '6:00AM'],
            series: [
                [287, 385, 490, 562, 594, 626, 698, 895, 952],
                [67, 152, 193, 240, 387, 435, 535, 642, 744],
                [23, 113, 67, 108, 190, 239, 307, 410, 410]
            ]
        };
    
        var optionsSales = {
            lineSmooth: false,
            low: 0,
            high: 1000,
            showArea: true,
            height: "245px",
            axisX: {
                showGrid: false,
            },
            lineSmooth: Chartist.Interpolation.simple({
                divisor: 3
            }),
            showLine: true,
            showPoint: false,
        };
    
        var responsiveSales = [
            ['screen and (max-width: 640px)', {
                axisX: {
                    labelInterpolationFnc: function (value) {
                        return value[0];
                    }
                }
            }]
        ];
    
        Chartist.Line('#chartHours', dataSales, optionsSales, responsiveSales);
</script>
{% endblock %}

customers/templates/customers/profile.html
{% extends "customers/base.html" %}
{% load static %}


 {% block title %} 
    Profile
 {% endblock %}

{% block content %}
<div class="row">

    <div class="col-lg-3 col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img src="{% static "assets/img/background.jpg" %}" alt="..."/>
                </div>
                <div class="content">
                    <div class="author">
                        <img class="avatar border-white" src="assets/img/faces/face-2.jpg" alt="..."/>
                        <h4 class="title">Chet Faker<br />
                            <a href="#"><small>@chetfaker</small></a>
                        </h4>
                    </div>
                    <p class="description text-center">
                        "I like the way you work it <br>
                        No diggity <br>
                        I wanna bag it up"
                    </p>
                </div>
                <hr>
                
            </div>
            
                
    </div>

    <div class="col-lg-9 col-md-8">
        <div class="card">
            <div class="header">
                <h4 class="title">Edit Profile</h4>
            </div>
            <div class="content">
                <form method="POST">
                        {% csrf_token %}
                    <!-- <div class="row">
                        <div class="col-md-5">
                            <div class="form-group">
                                <label>Company</label>
                                <input type="text" class="form-control border-input" disabled placeholder="Company" value="Creative Code Inc.">
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" class="form-control border-input" placeholder="Username" value="michael23">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Email address</label>
                                <input type="email" class="form-control border-input" placeholder="Email">
                            </div>
                        </div>
                    </div> -->

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control border-input" name="first_name" placeholder="Last Name" value="{{request.user.profile.first_name}}" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control border-input" name="last_name" placeholder="Last Name" value="{{request.user.profile.last_name}}" />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Address</label>
                                <input type="text" class="form-control border-input" name="address" placeholder="Address" value="{{request.user.profile.address}}">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>City</label>
                                <input type="text" class="form-control border-input" name="city" placeholder="City" value="{{request.user.profile.city}}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Country</label>
                                <input type="text" class="form-control border-input" name="country" placeholder="Country" value="{{request.user.profile.country}}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Postal Code</label>
                                <input type="text" class="form-control border-input" name="zip_code" placeholder="Zip Code" value="{{request.user.profile.zip_code}}">
                            </div>
                        </div>
                    </div>

                    <!-- <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>About Me</label>
                                <textarea class="form-control border-input" name="bio"  placeholder="Your Biography" value="{{request.user.profile.bio}}"></textarea>
                            </div>
                        </div>
                    </div> -->
                    <div class="text-center">
                        <button type="submit" class="btn btn-info btn-fill btn-wd">Update Profile</button>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>


</div>
{% endblock %}

customers/templates/customers/send_money.html
{% extends "customers/base.html" %}

 {% block title %}
 Send Money
 {% endblock %}

{% block content %}
<div class="row">

    <form method="POST">
        {% csrf_token %}

        <div class="form-group">

            {{ form.from_account }}

        </div>

        <div class="form-group">

            {{ form.to_account }}

        </div>

        <div class="form-group">

            {{ form.amount }}

        </div>

        <input type="submit" value="Send" class="btn btn-primary" />
    </form>
</div>
{% endblock %}

customers/templates/customers/transactions.html
{% extends "customers/base.html" %}

 {% block title %} 
    Transaction History
 {% endblock %}

{% block content %}
<div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">History</h4>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-striped">
                        <thead>
                        <th>ID</th>
                        <th>From Account</th>
                        <th>To Account</th>
                        <th>Amount</th>
                        <th>Date</th>
                        </thead>
                        <tbody>

                            {% for item in transaction  %}
                                <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.from_account }}</td>
                                    <td>{{ item.to_account }}</td>
                                    <td>${{ item.amount }}</td>
                                    <td>{{ item.date_created }}</td>
                                </tr>
                            {% endfor %}
                                
                        </tbody>
                    </table>
    
                </div>
            </div>
        </div>
    </div>
{% endblock %}